name: Continuous Integration
on: [push]

jobs:
  build:
    env:
      NPM_TOKEN: SECRET_NPM_TOKEN
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install
        run: npm install
      - name: Lint
        run: |
          npm run lint
          npm run format:check
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
