name: tagged-release
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: install
        run: npm install
      - name: Publish To NPM
        run: npm run publish:all
